dist: bionic

language: c

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnotify-dev libsystemd-dev afl

env: AFL_NO_UI=1 AFL_EXIT_WHEN_DONE=1

jobs:
  include:
    - script:
      - sudo sh -c 'echo core > /proc/sys/kernel/core_pattern'
      - 'timeout -s INT --preserve-status 5m make fuzz-pressures; [[ $? == 130 ]]'
      - 'if (( "$(ls -A fuzz/pressures/results/crashes | wc -l)" != 0 )); then grep . fuzz/pressures/results/crashes/*; exit 1; fi'

    - script:
      - sudo sh -c 'echo core > /proc/sys/kernel/core_pattern'
      - 'travis_wait 30 timeout -s INT --preserve-status 30m make fuzz-configs; [[ $? == 130 ]]'
      - 'if (( "$(ls -A fuzz/pressures/results/crashes | wc -l)" != 0 )); then grep . fuzz/pressures/results/crashes/*; exit 1; fi'

    - script: make
    - script: make clang-tidy
    - script: make clang-everything

    - script: make WANT_SD_NOTIFY=0
    - script: make clang-tidy WANT_SD_NOTIFY=0
    - script: make clang-everything WANT_SD_NOTIFY=0
